#                                                                        #
# "Service" subroutes configuration for the TYPO3.Neos package           #
#                                                                        #


# The demo action

-
  name: 'NetlogixJsonApiOrgExampleDataSubroutes'
  uriPattern: ''
  defaults:
    '@package':    'Netlogix.JsonApiOrg.ExampleData'
    '@controller': 'Node'
    '@action':     'demo'
    '@format':     'html'

# RESTful routes for Nodes service

-
  name: 'Nodes - index'
  uriPattern: 'nodes'
  defaults:
    '@package':    'Netlogix.JsonApiOrg.ExampleData'
    '@controller': 'Node'
    '@action':     'index'
    '@format':     'json'

-
  name: 'Nodes - show'
  uriPattern: 'nodes/{node}'
  defaults:
    '@package':    'Netlogix.JsonApiOrg.ExampleData'
    '@controller': 'Node'
    '@action':     'index'
    '@format':     'json'

-
  name: 'Nodes - relationship'
  uriPattern: 'nodes/{node}/relationships/{relationshipName}'
  defaults:
    '@package':    'Netlogix.JsonApiOrg.ExampleData'
    '@controller': 'Node'
    '@action':     'index'
    '@format':     'json'

-
  name: 'Nodes - related'
  uriPattern: 'nodes/{node}/{relationshipName}'
  defaults:
    '@package':    'Netlogix.JsonApiOrg.ExampleData'
    '@controller': 'Node'
    '@action':     'showRelated'
    '@format':     'json'
